### ISSUE TITLE
consider removing email auto-fill

### ISSUE THREAD

**Issue by samkusnetz** [Figure53/F53FeedbackKit#12]
too many users are confused by, or paranoid about, the modal asking for permission to access contacts.

**Comment by c-had** [comment]
We can certainly consider it, though it runs counter to the previous push to get more users to submit their email addresses (e.g. issue #3 ). This is certainly technically possible, but I imagine it'll lead to a drop in email addresses on feedback submissions if users have to type it themselves.

**Comment by samkusnetz** [comment]
as an alternative, i would enjoy some kind of increased harassment if the email field is blank when they hit submit. "no email, really? we won't be able to write back!"

**Comment by c-had** [comment]
That's already done (issue #3 ). It was implemented in 2013, but we dropped the ball on importing the updated FeedbackKit into QLab (we've needed a project manager for some time). Maybe we should finally do that 😞

**Comment by samkusnetz** [comment]
ah ah, sorry, i'm not yet very adept at following issue threads between repos. thank you!

**Comment by c-had** [comment]
Oh, you don't need to apologize. I'm just annoyed at myself for never getting it into QLab.
