### ISSUE TITLE
Extend log history collected to at least 1 week

### ISSUE THREAD

**Issue by SoundGuyAndy** [Figure53/F53FeedbackKit#7]
I only just learned that we only collect 24 hours of logs in submitted reports. I've had to turn a number of support tickets away because the logs only went back a day, and the problem happened a day or two earlier, but they hadn't had time to write in. I didn't even know it was on our end, to be honest, I thought it was Apple glitching in the logs and cycling old stuff out. 

It's still arbitrary, but I think at least a week would be a lot more helpful in being able to search for patterns and that sort of thing.

**Comment by c-had** [comment]
I was thinking this would be a big increase in server load, but I had forgotten that including console logs was already an opt-in checkbox, so most reports don't include it. Seems like less of a problem, then.

Note that F53FeedbackKit already supports this by setting the FRFeedbackReporter.logHours Info.plist key to however many hours you like. There may be a case for changing the default away from 24 hours, but I'd lean toward keeping it 24 hours and having the apps that use it change the value in their Info.plist.

**Comment by ChrisAshworth** [comment]
I support @c-had's approach. I've updated it in QLab to use 1 week, since it makes sense there. I agree the default for the framework should remain at 24 hours.
